/*
 * Sky Leilani
 * 2.29.2019
 * Help found at:
 *
 * http://www.cplusplus.com/reference/cstdlib/rand/ for random function and stdlib.h
 * https://www.youtube.com/watch?v=agjVX-5m3ss for finding even/odd number
 */
#include <stdlib.h> // library including rand() function
#include <iostream> // this allows me to use cout

using namespace std; // says we are using the c++ standard library region's symbols


int evenOddOrZero(int number) { // function takes number in parameter and returns with 1 if even, 0 if number is 0, and -1 if number is odd

    if(number%2 == 0) { // if the remainder of the number and 2 is 0, the number is even, return 1
        return 1;
    }
    else if(number == 0) { // if the number is 0, return 0
        return 0;
    }
    else { // if the remainder is anything other than 2, and is therefore odd, return -1
        return -1;
    }
}


int getRandomInt() { // function returns a random number between 0 - 99
    int random = rand() % 100; // setting var random to a random number divided by 100's remainder. Any number equal to
                                // or over 100 modulo 100 will be 0, which sets the max value of our function's return to 99
    return random;
}


int main() {

    int i = 0; // setting up the counter for while loop
    int numb;
    int randm_numb;
    while(i<10) { // this is setting the loop to maximum of 10

        randm_numb = getRandomInt(); // setting variable randm_numb to a pseudo random number generated by getRandomInt()
        numb = evenOddOrZero(randm_numb); // setting variable numb to either a 1, -1, or 0 based on the parity of the random number

        if(numb == 1) { // if the number generated by evenOddOrZero is 1...
            cout << randm_numb << " is even"<< endl; // then say it is even
        }

        else if(numb == -1){ // if the number generated by evenOddOrZero is -1...
            cout << randm_numb << " is odd" << endl; // then say it is odd

        }

        i++; // increments by 1


    }

    return 0; // we are done with the main function

}

